[pytest]
# Use spaces or newlines for multiple paths on Windows
pythonpath = 
    packages/pyshape/src
    packages/pymath/src

# This prevents 'tests' name collisions by appending the full path to sys.path
addopts = --import-mode=importlib --cov=packages --cov-report=xml --cov-report=term --verbose

# Test discovery
testpaths = 
    packages/pyshape/tests 
    packages/pymath/tests

python_files = test_*.py

# Minimum Python version
minversion = 6.0

markers =
    unit: marks tests as unit tests
    integration: marks tests as integration tests
    slow: marks tests as slow