sonar.projectKey=pyshape-project
sonar.projectName=PyShape
sonar.projectVersion=1.0
sonar-token=sqp_9b789b08afe7e458add5a756c42bbd66dd333395 
sonar.projectKey=manisha-csorg_python-project 
sonar.organization=manisha-csorg

#sonar.sources=src,copybooks
sonar.sources=src
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.xml,**.xhtml
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml




