sonar.projectKey=pyshape-project
sonar.projectName=PyShape
sonar.projectVersion=2.0
#sonar-token=sqp_bf1ca5c5cbcc9d2d74501f0bf6a042d7b4acecb4 
sonar.token=sqa_ab8a2207528b65c8744e88fc6a0c45c3fcc825c2
sonar.projectKey=manisha-csorg_python-project 
sonar.organization=manisha-csorg

#sonar.sources=src,copybooks
sonar.sources=src
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/*.xml,**.xhtml
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=tests/**/*
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.projectVersion=1.0




